Fix conflict with Revolution Slider
JDI-company/Smart-Phone-for-Ninja-Forms pull request #87
Opened 2024-10-02 06:12 UTC by max10110

2024-10-04 11:08 UTC, yaroslav-borodii approved these changes

2025-02-04 13:27 UTC, yaroslav-borodii commented
@GooodGod said that we still have some issues with this plugin.

Fix should be retested and fixed again if needed by @GooodGod.

2025-02-04 13:28 UTC, yaroslav-borodii requested changes
Check comment above

2025-02-28 14:09 UTC, GooodGod commented
The other error probably was on the slider's side(the error was that the slider couldn't get the carousel block, but it disappeared when the addon was disabled), it doesn't appear after updating WP to 6.7.2, everything works correct now.

2025-03-06 16:17 UTC, merged